### ISSUE TITLE
RRC timer considerations

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-tls13-iot#18]
RRC defines a timer value associated with the path validation algorithm with a default value of 1s.  This may not be OK in certain  IoT settings - for example, observed RTTs in NB-IoT are ~2.5s.
We need to work out whether there is any guidance we can provide in this area.

**Comment by OR13** [comment]
Perhaps a case analysis?

When is this timing issue a problem, when is it not?

**Comment by thomas-fossati** [comment]
> Thomas and I will chat with Achim. Will use RRC implementation on NBIOT for some numbers

@boaks you have been summoned :-)

**Comment by boaks** [comment]
> When is this timing issue a problem, when is it not?

There are usually also other timers, which are also not negotiated. And depending on the transmission layer (since a couple of days a had the chance to get some very first impression for NB-IoT via satellite) even those 2.5s are much to less (10-15s). So FMPOV, it will require anyway a "configuration" for a lot of cases. The "default" seems for me to be therefore not that important.

**Comment by thomas-fossati** [comment]
Thanks Achim!  We'll work on incorporating your suggestions.
