### ISSUE TITLE
Improve text around client cert profile

### ISSUE THREAD

**Issue by thomas-fossati** [thomas-fossati/draft-tls13-iot#22]
From [MCR review](https://mailarchive.ietf.org/arch/msg/uta/i5rhYTl_EhhJSEwwH4FbA4XwnIA/):

```
Validation of client certificates (whether factory provisioned IDevIDs, or
locally enrolled LDevIDs) is a topic that I care a lot about, and
this text is inadequate.

As the (industrial) IoT market embraces IDevID certificates, there is some
concern that different markets will put different requirements on IDevID
contents.  So far it does not appear that anyone has created a situation
where a single (fat) IDevID certificate couldn't be used in a variety of
market verticals, the concern remains.

It was my intention to introduce a document about this issue. I think that
it's something that only the IETF can do.  Perhaps that would fit into this
UTA document, or perhaps parts of this section 15 goes into another document.
```

**Comment by mcr** [comment]
@mcr bread crumbs.

**Comment by OR13** [comment]
@mcr how can we make this issue more actionable?

Can you propose some text?

Are you asking for the section to be removed?

**Comment by mcr** [comment]
Re-reading -05, since it's been awhile.
* subjectPublicKeyInfo: should be made mandatory by this profile.
* Root CA Certificate: I don't understand why constraints on this, it's a trust anchor, not a certificate.  As such, it needs to be marked with whatever capabilities are relevant, when the trust anchor is loaded into the trust store.
* subordinate CA: pathLenConstraint MAY be present, but you haven't said if it needs to be evaluated :-)
* EE _extendedKeyUsage MUST be present and contain at least one of id-kp-serverAuth or id-kp-clientAuth_  IDevID, 802.1AR generally says that EKU should not be present, because IDevID SHOULD be as useful as possible, and EKU restricts useability significantly.  This is a thing where generalized uses really beat out legal nonsense with EKU.
** But maybe you are trying to ail down the server certificate for a device that calls home, if so you need to say that

_Avoid deep and complex CA hierarchies to reduce the number of subordinate CA certificates that need to be transmitted._  I suggest you reference https://www.ietf.org/archive/id/draft-irtf-t2trg-taxonomy-manufacturer-anchors-00.html#name-number-of-levels-of-certification here.

_Use session resumption to reduce the number of times a full handshake is needed. Use Connection IDs [DTLS-CID], when possible, to enable long-lasting connections._
I have wondered whether some devices might initiate a TLS session in the factory, load a session resumption ticket valid for years to decades, and just ALWAYS use that.

_Use client certificate URLs [[RFC6066](https://www.ietf.org/archive/id/draft-ietf-uta-tls13-iot-profile-05.html#RFC6066)] instead of full certificates for clients._
please also reference https://datatracker.ietf.org/doc/draft-ietf-dance-tls-clientid/

_Whether to utilize any of the above extensions or a combination of them depends on the anticipated deployment environment, the availability of code, and the constraints imposed by already deployed infrastructure (e.g., CA infrastructure, tool support)._
too wishy-washy.  Let's actually set some goals that people can code against, and that enterprises can specify that they want.
(Section 18 is way more specific, and I like that)

**Comment by thomas-fossati** [comment]
ACTION(@mcr): check that the current text works - especially, around extended key usage for IDevIDs.
